services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ../PrimeMotors-backend
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../PrimeMotors-backend/.env
    networks:
      - internal

  frontend:
    build:
      context: ../PrimeMotors-FrontEnd
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/ssl:ro   # certificados SSL
    depends_on:
      - backend
    networks:
      - internal

volumes:
  mysql_data:

networks:
  internal:
    driver: bridge